import type { LlmClient, LlmCompletion, LlmCompleteOptions } from './index.js';

const DEFAULT_TOKENS = {
  name: 'Untitled Brand',
  version: 1,
  description: 'Generated by fake LLM provider for development',
  colors: { primary: '#0091DA', accent: '#1B365D', surface: '#FFFFFF', on_surface: '#1A1C1E' },
  typography: {
    heading: { family: 'Inter', weights: [600, 700] },
    body: { family: 'Inter', weights: [400, 500] },
  },
  rounded: { sm: 4, md: 8, lg: 16 },
  spacing: { unit: 8, scale: [4, 8, 16, 24, 32, 48] },
  components: {},
  vpa: {
    voice: { tone: 'Confident, clear', avoid: ['jargon'] },
    audio: { music_mood: 'uplifting', sonic_logo: null },
    logo: { primary: null, mono: null, safe_zone_ratio: 0.25 },
    lower_thirds: { template: 'bar-left-accent', bg: '{colors.primary}', fg: '{colors.surface}' },
    taglines: [],
  },
};

const SAMPLE_BODY = `## Overview

The brand is built on confidence and clarity. Every visual choice serves a single goal: communicate substance without ornament.

## Colors

The primary color anchors the brand. Surface is the canvas. On-surface is the ink.

## Typography

Inter handles both display and reading roles. Heading weights carry hierarchy; body weights carry rhythm.

## Layout

The 8px grid is the unit of all spacing. Use the scale conservatively.

## Elevation & Depth

Elevation is communicated through subtle shadow and color shift, never lines.

## Shapes

Rounded corners are gentle. Sharp corners signal density.

## Components

Components inherit token values directly — never one-off color choices.

## Do's and Don'ts

- Do let whitespace breathe.
- Don't add decoration that doesn't carry meaning.

## Voice & Tone

Confident and clear. We say what we mean and stop.

- Do: "Build cloud-native, faster."
- Don't: "Embark on a transformative journey to unlock synergies."

## Audio

Music is uplifting and forward-leaning, never frantic.

## Logo Usage

Maintain the safe zone. Use the mono variant on busy backgrounds.
`;

export function createFakeLlm(): LlmClient {
  return {
    async complete(opts: LlmCompleteOptions): Promise<LlmCompletion> {
      if (opts.responseFormat === 'json') {
        const nameMatch = opts.userPrompt.match(/<<NAME=([^>]+)>>/);
        const name = nameMatch ? nameMatch[1]!.trim() : DEFAULT_TOKENS.name;
        const tokens = { ...DEFAULT_TOKENS, name };
        return { text: JSON.stringify(tokens, null, 2) };
      }
      return { text: SAMPLE_BODY };
    },
  };
}
