import type { LlmClient, LlmCompletion, LlmCompleteOptions } from './index.js';

const DEFAULT_TOKENS = {
  version: 'alpha',
  name: 'Untitled Brand',
  description: 'Generated by fake LLM provider for development',
  colors: {
    primary: '#0091DA',
    secondary: '#1B365D',
    neutral: '#FFFFFF',
    'on-surface': '#1A1C1E',
  },
  typography: {
    'headline-lg': { fontFamily: 'Inter', fontSize: '36px', fontWeight: 700, lineHeight: 1.2 },
    'headline-md': { fontFamily: 'Inter', fontSize: '28px', fontWeight: 700, lineHeight: 1.3 },
    'body-md':     { fontFamily: 'Inter', fontSize: '16px', fontWeight: 400, lineHeight: 1.5 },
    'body-sm':     { fontFamily: 'Inter', fontSize: '14px', fontWeight: 400, lineHeight: 1.5 },
    'label-md':    { fontFamily: 'Inter', fontSize: '14px', fontWeight: 700, lineHeight: 1.4 },
  },
  rounded: { sm: '4px', md: '8px', lg: '16px' },
  spacing: { xs: '4px', sm: '8px', md: '16px', lg: '24px', xl: '32px', xxl: '48px' },
  components: {
    'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.neutral}', rounded: '{rounded.sm}' },
    card: { backgroundColor: '{colors.neutral}', textColor: '{colors.on-surface}', rounded: '{rounded.md}' },
  },
  vpa: {
    voice: { tone: 'Confident, clear', avoid: ['jargon'] },
    audio: { music_mood: 'uplifting', sonic_logo: null },
    logo: { primary: null, mono: null, safe_zone_ratio: 0.25 },
    lower_thirds: { template: 'bar-left-accent', bg: '{colors.primary}', fg: '{colors.neutral}' },
    taglines: [],
  },
};

const SAMPLE_BODY = `## Overview

The brand is built on confidence and clarity. Every visual choice serves a single goal: communicate substance without ornament. The palette is rooted in strong blues with a clean neutral background.

## Colors

The primary color (#0091DA) anchors the brand across headlines and interactive elements. Secondary (#1B365D) provides depth for supporting elements. Neutral (#FFFFFF) is the primary surface. On-surface (#1A1C1E) is the default text color. All pairings meet WCAG AA contrast requirements.

## Typography

The type system uses Inter throughout. Headline-lg (36px/700) for primary titles, headline-md (28px/700) for section headers, body-md (16px/400) for readable content, body-sm (14px/400) for secondary text, and label-md (14px/700) for interactive labels.

## Layout

The spacing scale follows a 4–48px progression (xs through xxl). Use the scale consistently — do not invent intermediate values.

## Shapes

Corners follow a graduated scale: sm (4px), md (8px), lg (16px). Use sm for buttons and inputs, md for cards, lg for modals and popovers.

## Components

Button-primary uses the primary color with neutral text and sm rounding. Cards use neutral backgrounds with on-surface text and md rounding. Components always reference design tokens — never use raw color values.

## Do's and Don'ts

**Do:**
- Let whitespace breathe
- Reference design tokens in all components
- Maintain WCAG AA contrast ratios

**Don't:**
- Add decoration that doesn't carry meaning
- Use off-brand colors or one-off values
- Mix typography levels inconsistently
`;

const IDEATION_RESPONSE = `Great idea! I've broken this down into a logical sequence of scenes that will walk the viewer through the full workflow.

Here's my proposed storyboard:

\`\`\`json
{"scenes": [
  {"id": "scene-01", "name": "Introduction and Context", "description": "Open with a brief overview of what we're building and why. Show the end result first to hook the viewer, then explain we'll walk through the setup step by step.", "type": "desktop"},
  {"id": "scene-02", "name": "Prerequisites and Setup", "description": "Show the tools and dependencies needed. Walk through installing or verifying each prerequisite is in place before we begin the main configuration.", "type": "terminal"},
  {"id": "scene-03", "name": "Core Configuration", "description": "The main event — walk through the primary configuration step by step. Show each file edit, each setting change, explaining what each option does and why we chose these values.", "type": "desktop"},
  {"id": "scene-04", "name": "First Run and Verification", "description": "Run the configured system for the first time. Show the expected output, verify everything is working correctly, and troubleshoot any common issues.", "type": "terminal"},
  {"id": "scene-05", "name": "Practical Usage Demo", "description": "Now that everything is set up, demonstrate a real-world use case. Show the system solving an actual problem the viewer would encounter in their daily work.", "type": "browser"},
  {"id": "scene-06", "name": "Recap and Next Steps", "description": "Summarize what we accomplished, highlight key takeaways, and point the viewer to additional resources or advanced topics they can explore on their own.", "type": "desktop"}
]}
\`\`\`

Each scene is designed to be 30-60 seconds, keeping the total demo under 5 minutes. Want me to adjust any scenes or add more detail to specific sections?`;

const IDEATION_REFINE_RESPONSE = `Good call — I've updated the scenes based on your feedback.

\`\`\`json
{"scenes": [
  {"id": "scene-01", "name": "Introduction and Context", "description": "Open with a brief overview of what we're building and why. Show the end result first to hook the viewer, then explain we'll walk through the setup step by step.", "type": "desktop"},
  {"id": "scene-02", "name": "Prerequisites and Setup", "description": "Show the tools and dependencies needed. Walk through installing or verifying each prerequisite is in place before we begin the main configuration.", "type": "terminal"},
  {"id": "scene-03", "name": "Core Configuration", "description": "The main event — walk through the primary configuration step by step. Show each file edit, each setting change, explaining what each option does and why we chose these values.", "type": "desktop"},
  {"id": "scene-04", "name": "First Run and Verification", "description": "Run the configured system for the first time. Show the expected output, verify everything is working correctly, and troubleshoot any common issues.", "type": "terminal"},
  {"id": "scene-05", "name": "Practical Usage Demo", "description": "Now that everything is set up, demonstrate a real-world use case. Show the system solving an actual problem the viewer would encounter in their daily work.", "type": "browser"},
  {"id": "scene-06", "name": "Recap and Next Steps", "description": "Summarize what we accomplished, highlight key takeaways, and point the viewer to additional resources or advanced topics they can explore on their own.", "type": "desktop"}
]}
\`\`\`

I've refined the storyboard. Let me know if you want to adjust anything else, or accept this storyboard to move forward!`;

function isIdeationPrompt(opts: LlmCompleteOptions): boolean {
  return opts.systemPrompt.toLowerCase().includes('ideation') ||
    opts.systemPrompt.toLowerCase().includes('storyboard') ||
    opts.systemPrompt.toLowerCase().includes('demo video planner');
}

function isSceneDescriptionPrompt(opts: LlmCompleteOptions): boolean {
  const lower = opts.systemPrompt.toLowerCase();
  return lower.includes('scene name and description') &&
    !lower.includes('demo video planner');
}

function isNarrationWriterPrompt(opts: LlmCompleteOptions): boolean {
  return opts.systemPrompt.toLowerCase().includes('narration script writer');
}

function isNarrationPolishPrompt(opts: LlmCompleteOptions): boolean {
  return opts.systemPrompt.toLowerCase().includes('narration script polisher');
}

function isLowerThirdPrompt(opts: LlmCompleteOptions): boolean {
  return opts.systemPrompt.toLowerCase().includes('lower-third recommender');
}

function isQualityReviewPrompt(opts: LlmCompleteOptions): boolean {
  return opts.systemPrompt.toLowerCase().includes('quality review');
}

function isShotPlanPrompt(opts: LlmCompleteOptions): boolean {
  return opts.systemPrompt.toLowerCase().includes('shot plan author');
}

function isSceneSplitterPrompt(opts: LlmCompleteOptions): boolean {
  const lower = opts.systemPrompt.toLowerCase();
  return lower.includes('scene splitter') && !lower.includes('scene name and description');
}

export function createFakeLlm(): LlmClient {
  let ideationCallCount = 0;
  return {
    async complete(opts: LlmCompleteOptions): Promise<LlmCompletion> {
      // Scene splitter — propose boundaries from a single recording
      if (isSceneSplitterPrompt(opts)) {
        const durationMatch = opts.userPrompt.match(/Duration:\s*([\d.]+)/);
        const totalDuration = durationMatch?.[1] ? parseFloat(durationMatch[1]) : 180;
        const sceneCount = 3;
        const sceneDuration = totalDuration / sceneCount;
        const boundaries = Array.from({ length: sceneCount }, (_, i) => ({
          start_sec: Math.round(sceneDuration * i * 100) / 100,
          end_sec: Math.round(sceneDuration * (i + 1) * 100) / 100,
          suggested_name: ['Introduction and Setup', 'Core Feature Demo', 'Summary and Wrap-up'][i],
        }));
        return { text: JSON.stringify(boundaries) };
      }

      // Quality review
      if (isQualityReviewPrompt(opts)) {
        return {
          text: JSON.stringify([
            { sceneId: 'scene-01', severity: 'info', category: 'description', message: 'Scene description is clear and actionable.' },
            { sceneId: 'scene-02', severity: 'warn', category: 'recording', message: 'No recording uploaded yet.' },
            { sceneId: 'scene-03', severity: 'warn', category: 'script', message: 'No narration script generated.' },
            { sceneId: 'scene-04', severity: 'info', category: 'lower_thirds', message: 'Lower thirds look good.' },
          ]),
        };
      }

      // Lower-third recommender. Prompt label changed from `Scene:` to
      // `Scene name:` when LT input gained intent + objective + audience;
      // accept both forms so legacy fixture cases keep working.
      if (isLowerThirdPrompt(opts)) {
        const nameMatch = opts.userPrompt.match(/Scene name:\s*(.+)/) ?? opts.userPrompt.match(/Scene:\s*(.+)/);
        const sceneName = nameMatch?.[1]?.trim() ?? 'Demo Scene';
        return {
          text: JSON.stringify([
            { title: sceneName, subtitle: 'Getting Started', style: 'frosted', in_sec: 1.5, out_sec: 5.5 },
            { title: 'Key Concept', style: 'minimal', in_sec: 12.0, out_sec: 16.0 },
          ]),
        };
      }

      // Narration polish — editor mode over a user-supplied draft. Returns
      // the { notes, script } JSON contract the polishScript service parses.
      // Must come before the narration-writer branch (both mention "narration
      // script") and before the generic json branch.
      if (isNarrationPolishPrompt(opts)) {
        const nameMatch = opts.userPrompt.match(/Scene name:\s*(.+)/);
        const sceneName = nameMatch?.[1]?.trim() ?? 'this scene';
        return {
          text: JSON.stringify({
            notes: [
              `Tightened the opening for ${sceneName}.`,
              'Added emotive tags for spoken delivery.',
            ],
            script:
              `[warm] Here's a polished take on ${sceneName}.\n\n` +
              `[confident] The key steps stay exactly as you wrote them, just tighter.\n\n` +
              `[calm] And that wraps up this part.`,
          }),
        };
      }

      // Narration script generation. Same prompt-label evolution as LT.
      if (isNarrationWriterPrompt(opts)) {
        const nameMatch = opts.userPrompt.match(/Scene name:\s*(.+)/) ?? opts.userPrompt.match(/Scene:\s*(.+)/);
        const sceneName = nameMatch?.[1]?.trim() ?? 'this scene';
        return {
          text: `[warm] Let's take a look at ${sceneName}. This is where things really come together.\n\n[confident] Notice how we walk through each step carefully. Every action here builds on what we set up earlier.\n\n[thoughtful] The key thing to understand is why this matters — it's not just about the configuration, it's about establishing a pattern you can reuse.\n\n[calm] And that's it for this section. Let's move on to what comes next.`,
        };
      }

      // Video analysis / scene description (must come before ideation — both prompts contain "storyboard")
      if (isSceneDescriptionPrompt(opts)) {
        const sceneMatch = opts.userPrompt.match(/Scene (\d+) of (\d+)/);
        const sceneNum = sceneMatch?.[1] ? parseInt(sceneMatch[1], 10) : 1;
        return {
          text: JSON.stringify({
            name: `Scene ${sceneNum} Demo`,
            description: `This scene demonstrates step ${sceneNum} of the workflow. The recording shows the key actions and configuration needed for this part of the demo.`,
            type: sceneNum % 2 === 0 ? 'terminal' : 'desktop',
          }),
        };
      }

      // Shot-plan (must come before ideation — prompt may contain "storyboard")
      if (isShotPlanPrompt(opts)) {
        return {
          text:
            "Here's a first pass — tell me anything I should make more specific.\n\n" +
            '```json\n' +
            '{"steps":[' +
            '{"index":1,"action":"Open a new Terminal window"},' +
            '{"index":2,"action":"Type `npm run dev` and press Enter","note":"Wait for the ready line"},' +
            '{"index":3,"action":"Show the rendered page in the browser"}' +
            ']}\n' +
            '```',
        };
      }

      // Ideation requests
      if (isIdeationPrompt(opts)) {
        ideationCallCount++;
        if (ideationCallCount === 1) {
          return { text: IDEATION_RESPONSE };
        }
        return { text: IDEATION_REFINE_RESPONSE };
      }

      // Brand token extraction (JSON)
      if (opts.responseFormat === 'json') {
        const nameMatch = opts.userPrompt.match(/<<NAME=([^>]+)>>/);
        const name = nameMatch ? nameMatch[1]!.trim() : DEFAULT_TOKENS.name;
        const tokens = { ...DEFAULT_TOKENS, name };
        return { text: JSON.stringify(tokens, null, 2) };
      }

      // Brand rationale (default)
      return { text: SAMPLE_BODY };
    },
  };
}
